In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        ' I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 ' I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## define the vocablory size
voc_size = 10000


In [8]:
### one hot representation of the sentences
one_hot_repr = [one_hot(word, voc_size) for word in sent]
one_hot_repr

[[7875, 2047, 4057, 8701],
 [7875, 2047, 4057, 305],
 [7875, 1923, 4057, 5801],
 [3496, 7506, 2542, 7689, 7744],
 [3496, 7506, 2542, 7689, 2615],
 [345, 7875, 7741, 4057, 3894],
 [1071, 3680, 9880, 7689]]

In [10]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np


In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 7875, 2047, 4057, 8701],
       [   0,    0,    0,    0, 7875, 2047, 4057,  305],
       [   0,    0,    0,    0, 7875, 1923, 4057, 5801],
       [   0,    0,    0, 3496, 7506, 2542, 7689, 7744],
       [   0,    0,    0, 3496, 7506, 2542, 7689, 2615],
       [   0,    0,    0,  345, 7875, 7741, 4057, 3894],
       [   0,    0,    0,    0, 1071, 3680, 9880, 7689]])

In [14]:
## Feature representation using embedding
dim = 10 # 10 features for each word

In [15]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 83ms/step


array([[[ 4.9042527e-02,  4.8450828e-03,  6.2847845e-03, -2.8837955e-02,
         -3.8052894e-02, -3.3737518e-02,  1.4287364e-02, -4.7653582e-02,
          9.0301149e-03, -3.2091632e-02],
        [ 4.9042527e-02,  4.8450828e-03,  6.2847845e-03, -2.8837955e-02,
         -3.8052894e-02, -3.3737518e-02,  1.4287364e-02, -4.7653582e-02,
          9.0301149e-03, -3.2091632e-02],
        [ 4.9042527e-02,  4.8450828e-03,  6.2847845e-03, -2.8837955e-02,
         -3.8052894e-02, -3.3737518e-02,  1.4287364e-02, -4.7653582e-02,
          9.0301149e-03, -3.2091632e-02],
        [ 4.9042527e-02,  4.8450828e-03,  6.2847845e-03, -2.8837955e-02,
         -3.8052894e-02, -3.3737518e-02,  1.4287364e-02, -4.7653582e-02,
          9.0301149e-03, -3.2091632e-02],
        [ 4.0849458e-02, -4.0397920e-02,  7.4065551e-03, -8.8930838e-03,
         -4.0578198e-02, -4.6146479e-02,  2.2064831e-02,  2.9898074e-02,
          2.2087228e-02,  3.0922625e-02],
        [-2.5827885e-02,  1.4286671e-02,  3.3361580e-02,  9.

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7875, 2047, 4057, 8701])

In [19]:
model.predict(embedded_docs)[0][0]

1/1 [==============================] - 0s 17ms/step


array([ 0.04904253,  0.00484508,  0.00628478, -0.02883795, -0.03805289,
       -0.03373752,  0.01428736, -0.04765358,  0.00903011, -0.03209163],
      dtype=float32)